app/account/urls.py
from django.urls import path

from account.views import (
    UserSignUpView, UserActivateView, ProfileView
)

app_name = 'account'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', UserActivateView.as_view(), name='activate'),
]

app/currency/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from currency.api.views import RateViewSet, SourceApiView, ContactUsViewSet

app_name = 'api-currency'

router = DefaultRouter()
router.register(r'rates', RateViewSet, basename='rates')
router.register(r'contactus', ContactUsViewSet, basename='contactus')

urlpatterns = [
    path('sources/', SourceApiView.as_view(), name='sources')
]

urlpatterns += router.urls

app/currency/urls.py
from django.urls import path

from currency.views import (
    RateListView,
    RateCreateView,
    RateDetailView,
    RateUpdateView,
    RateDeleteView,

    EmailListView,

    ContactUsCreateView,

    SourceListView,
    SourceCreateView,
    SourceDetailView,
    SourceUpdateView,
    SourceDeleteView,
)

app_name = 'currency'

urlpatterns = [
    path('sources/list/', SourceListView.as_view(), name='sources-list'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),

    path('emails/list/', EmailListView.as_view(), name='emails-list'),

    path('contactus/create/', ContactUsCreateView.as_view(), name='contact-us-create'),

    path('rates/list/', RateListView.as_view(), name='rates-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
]

app/settings/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

import settings.settings

from currency.views import IndexView

schema_view = get_schema_view(
   openapi.Info(
      title="Tracky API",
      default_version='v1',
      description="Open Tracky API",
      terms_of_service="https://www.tracky.io/terms/",
      contact=openapi.Contact(email="tracky@tracky.io"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('auth/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('', IndexView.as_view(), name='homepage'),

    path('currency/', include('currency.urls')),
    path('api/currency/', include('currency.api.urls')),
    path('api/', include('account.api.urls')),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.settings.base.MEDIA_URL, document_root=settings.settings.base.MEDIA_ROOT)

app/currency/models.py
from _decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models

from currency.choices import RateCurrencyChoices


# Create your models here.


class Rate(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    currency = models.PositiveSmallIntegerField(
        choices=RateCurrencyChoices.choices,
        default=RateCurrencyChoices.USD
    )
    buy = models.DecimalField(
        max_digits=6, decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'), message="Exchange rate can't be smaller than zero")])
    sell = models.DecimalField(
        max_digits=6, decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'), message="Exchange rate can't be smaller than zero")])
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return f'Currency: {self.get_currency_display()}, Buy: {self.buy} (id: {self.id})'


class ContactUs(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=128)
    email_from = models.EmailField(max_length=48)
    subject = models.CharField(max_length=48)
    message = models.TextField()

    class Meta:
        verbose_name_plural = 'emails'
        ordering = ('-created', )

    def __str__(self):
        return f'From: {self.email_from}, Subject{self.subject}'


class Source(models.Model):
    name = models.CharField(max_length=64)
    code_name = models.CharField(max_length=64, unique=True)
    source_url = models.CharField(max_length=255)
    logo = models.FileField(
        default='sources_logos/source-default.svg',
        upload_to='sources_logos/'
    )

    def __str__(self):
        return self.name


class RequestResponseLog(models.Model):
    path = models.CharField(max_length=255)
    request = models.CharField(max_length=16)
    time = models.FloatField()

app/currency/forms.py
from django import forms

from currency.models import Rate, Source, ContactUs


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            "buy",
            "sell",
            "source",
            "currency"
        )

        widgets = {
            'buy': forms.TextInput(attrs={'placeholder': '38.80'}),
            'sell': forms.TextInput(attrs={'placeholder': '39.20'}),
        }

        labels = {
            "buy": "Buy rate",
            "sell": "Sell rate"
        }


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            "name",
            "source_url",
            "logo"
        )

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Pryvatbank'}),
            'source_url': forms.TextInput(attrs={'placeholder': 'https://www.privatbank.ua/'}),
        }

        labels = {
            "source_url": "Source URL",
        }


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs

        fields = (
            "name",
            "email_from",
            "subject",
            "message"
        )

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Petro Poroshenko'}),
            'email_from': forms.TextInput(attrs={'placeholder': 'example@tracky.com'}),
            'subject': forms.TextInput(attrs={'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'placeholder': 'Enter your message...'})
        }

        labels = {
            "email_from": "Email",
            "message": "Your message"
        }

app/currency/api/views.py
from django.core.cache import cache
from requests import Response

from rest_framework import viewsets, generics
from rest_framework.decorators import action
from rest_framework.permissions import AllowAny
from rest_framework.renderers import JSONRenderer
from django_filters import rest_framework as filters
from rest_framework import filters as rest_framework_filters

from currency import constants
from currency.api.mixins import IsSuperUserMixin
from currency.api.serializers import RateSerializer, SourceSerializer, ContactUsSerializer
from currency.choices import RateCurrencyChoices
from currency.filters import EmailsFilter, RateAPIFilter
from currency.models import Rate, Source, ContactUs


class RateViewSet(viewsets.ModelViewSet):
    queryset = Rate.objects.all().select_related('source')
    serializer_class = RateSerializer
    renderer_classes = (JSONRenderer,)
    permission_classes = (AllowAny,)
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
    )
    filterset_class = RateAPIFilter
    ordering_fields = ('id', 'created', 'buy', 'sell')

    @action(detail=False, methods=('GET',))
    def latest(self, request, *args, **kwargs):
        latest_rates = []

        cached_rates = cache.get(constants.LATEST_RATE_CACHE)
        if cached_rates:
            return Response(cached_rates)

        for source_obj in Source.objects.all():
            for currency in RateCurrencyChoices:
                latest = Rate.objects.filter(
                    source=source_obj,
                    currency=currency) \
                    .order_by('-created') \
                    .first()

                if latest:
                    latest_rates.append(RateSerializer(instance=latest).data)

        cache.set(constants.LATEST_RATE_CACHE, latest_rates, 60 * 60 * 24 * 7)

        return Response(latest_rates)


class SourceApiView(generics.ListAPIView):
    queryset = Source.objects.all()
    serializer_class = SourceSerializer
    renderer_classes = (JSONRenderer,)


class ContactUsViewSet(IsSuperUserMixin, viewsets.ModelViewSet):
    queryset = ContactUs.objects.all()
    serializer_class = ContactUsSerializer
    renderer_classes = (JSONRenderer,)
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
        rest_framework_filters.SearchFilter,
    )
    filterset_class = EmailsFilter
    ordering_fields = ('created', 'name')
    search_fields = ['name', 'email_from', 'subject']

    def get_permissions(self):
        if self.action == 'list':
            permission_classes = (IsSuperUserMixin,)
        else:
            permission_classes = (AllowAny,)
        return [permission() for permission in permission_classes]

app/currency/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django_filters.views import FilterView

from currency.filters import RateFilter, EmailsFilter
from currency.models import Rate, ContactUs, Source
from currency.forms import RateForm, SourceForm, ContactUsForm

from currency.mixins import MyPaginatorMixin


# Create your views here.


# @method_decorator(cache_page(60 * 5), name='dispatch')
class RateListView(MyPaginatorMixin, FilterView):
    template_name = 'rates_list.html'
    paginate_by = 10
    filterset_class = RateFilter

    def get_queryset(self):
        return Rate.objects.all().select_related('source')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query_params = {key: value for key, value in self.request.GET.items() if
                        key != 'page' and value}
        context['filter_pagination'] = urlencode(query_params)
        return context


class RateDetailView(LoginRequiredMixin, DetailView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'


class RateCreateView(SuccessMessageMixin, CreateView):
    form_class = RateForm
    template_name = 'rate_create.html'
    success_url = reverse_lazy('currency:rates-list')
    success_message = 'Rate was created successfully'


class RateUpdateView(UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    form_class = RateForm
    template_name = 'rate_update.html'
    success_url = reverse_lazy('currency:rates-list')
    success_message = 'Rate was updated successfully'
    queryset = Rate.objects.all()

    def test_func(self):
        return self.request.user.is_superuser


class RateDeleteView(UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    queryset = Rate.objects.all()
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rates-list')
    success_message = 'Rate was deleted successfully'

    def test_func(self):
        return self.request.user.is_superuser


class EmailListView(MyPaginatorMixin, FilterView):
    template_name = 'emails_list.html'
    paginate_by = 10
    filterset_class = EmailsFilter

    def get_queryset(self):
        return ContactUs.objects.all()


class ContactUsCreateView(SuccessMessageMixin, CreateView):
    form_class = ContactUsForm
    template_name = 'contact_us_create.html'
    success_url = reverse_lazy('currency:contact-us-create')
    success_message = 'Your message was sent successfully'

    def _send_mail(self):
        subject = 'User ContactUs'
        message = f'''
                    Request from: {self.object.name}.
                    Reply to email: {self.object.email_from}.
                    Subject: {self.object.subject}.
                    Body: {self.object.message}.
                '''
        from currency.tasks import send_mail
        send_mail.delay(subject, message)

    def form_valid(self, form):
        redirect = super().form_valid(form)
        self._send_mail()
        return redirect


class SourceListView(ListView):
    template_name = 'sources_list.html'

    def get_queryset(self):
        return Source.objects.all()


class SourceDetailView(DetailView):
    queryset = Source.objects.all()
    template_name = 'source_details.html'


class SourceCreateView(SuccessMessageMixin, CreateView):
    form_class = SourceForm
    template_name = 'source_create.html'
    success_url = reverse_lazy('currency:sources-list')
    success_message = 'Source was created successfully'


class SourceUpdateView(SuccessMessageMixin, UpdateView):
    form_class = SourceForm
    template_name = 'source_update.html'
    success_url = reverse_lazy('currency:sources-list')
    success_message = 'Source was updated successfully'
    queryset = Source.objects.all()


class SourceDeleteView(SuccessMessageMixin, DeleteView):
    queryset = Source.objects.all()
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:sources-list')
    success_message = 'Source was deleted successfully'


class IndexView(TemplateView):
    template_name = 'index.html'

app/currency/templates/includes/filtering.html
{% load crispy_forms_tags %}

<div class="filter">
    <form method="get">
        <button type="button" class="btn btn-outline-primary dropdown-toggle" id="dropdownMenuButton">
            Filter
        </button>
        <div class="dropdown-menu filter-menu" style="width: 200px; padding: 10px;">
            <div class="form-body" style="max-height: 275px; overflow-y: auto;">
            {{ filter.form|crispy }}
            </div>
            <button type="submit" class="btn btn-primary mt-3">Apply</button>
        </div>
    </form>
</div>

<script>

    // Select the button element
    let button = $('#dropdownMenuButton');

    // Toggle the dropdown menu on click
    button.on('click', function (e) {
        e.preventDefault();
        button.dropdown('toggle');
    });

    // Hide the dropdown menu on click outside
    document.addEventListener('click', function (e) {
        // Get the clicked element
        let clicked = $(e.target);
        // If the clicked element is not the button or the menu or its children
        if (!clicked.is('#dropdownMenuButton') && !clicked.is('.dropdown-menu') && !clicked.closest('.dropdown-menu').length) {
            // Hide the dropdown
            button.dropdown('hide');
        }
    });

</script>

app/currency/templates/includes/footer.html
 <footer class="container d-flex flex-wrap justify-content-between align-items-center py-3 border-top mt-auto">
    <p class="col-md-3 mb-0 text-muted">© 2023 Tracky, Inc</p>

    <ul class="nav col-md-9 justify-content-end">
      <li class="nav-item"><a href="{% url 'homepage' %}" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="{% url 'currency:rates-list' %}" class="nav-link px-2 text-muted">Rates</a></li>
      <li class="nav-item"><a href="{% url 'currency:sources-list' %}" class="nav-link px-2 text-muted">Sources</a></li>
      <li class="nav-item"><a href="{% url 'currency:contact-us-create' %}" class="nav-link px-2 text-muted">Contact Us</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About Us</a></li>
    </ul>
  </footer>

app/currency/templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg" style="background-color: #f5f7ff;">
    <div class="container">
        <a class="navbar-brand" href="{% url 'homepage' %}">
            <img style="height:40px" src="{% static 'Tracky_logo.svg' %}">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'currency:rates-list' %}">Rates</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'currency:sources-list' %}">Sources</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'currency:contact-us-create' %}">Contact Us</a>
                </li>
                {% if request.user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'currency:emails-list' %}">Emails</a>
                </li>
                {% endif %}
            </ul>

            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ request.user.avatar.url }}" height="35px" class="navbar-avatar"> {{ request.user.email }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'account:profile' %}">Profile Settings</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'account:signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>

app/currency/templates/includes/pagination.html
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1&{{ filter_pagination }}">First</a></li>
            <li class="page-item"><a class="page-link"
                                     href="?page={{ page_obj.previous_page_number }}&{{ filter_pagination }}">&#129120;</a>
            </li>
            <li class="page-item"><a class="page-link"
                                     href="?page={{ page_obj.previous_page_number }}&{{ filter_pagination }}">{{ page_obj.previous_page_number }}</a>
            </li>
        {% endif %}

        <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ page_obj.next_page_number }}&{{ filter_pagination }}">{{ page_obj.next_page_number }}</a>
            </li>
            <li class="page-item"><a class="page-link"
                                     href="?page={{ page_obj.next_page_number }}&{{ filter_pagination }}">&#129122;</a>
            </li>
            <li class="page-item"><a class="page-link"
                                     href="?page={{ page_obj.paginator.num_pages }}&{{ filter_pagination }}">Last</a>
            </li>
        {% endif %}
    </ul>
</nav>