app/account/urls.py
from django.urls import path

from account.views import (
    UserSignUpView, UserActivateView, ProfileView
)

app_name = 'account'

urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', UserActivateView.as_view(), name='activate'),
]

app/currency/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from currency.api.views import RateViewSet, SourceApiView, ContactUsViewSet

app_name = 'api-currency'

router = DefaultRouter()
router.register(r'rates', RateViewSet, basename='rates')
router.register(r'contactus', ContactUsViewSet, basename='contactus')

urlpatterns = [
    path('sources/', SourceApiView.as_view(), name='sources')
]

urlpatterns += router.urls

app/currency/urls.py
from django.urls import path

from currency.views import (
    RateListView,
    RateCreateView,
    RateDetailView,
    RateUpdateView,
    RateDeleteView,

    EmailListView,

    ContactUsCreateView,

    SourceListView,
    SourceCreateView,
    SourceDetailView,
    SourceUpdateView,
    SourceDeleteView,
)

app_name = 'currency'

urlpatterns = [
    path('sources/list/', SourceListView.as_view(), name='sources-list'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),
    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),

    path('emails/list/', EmailListView.as_view(), name='emails-list'),

    path('contactus/create/', ContactUsCreateView.as_view(), name='contact-us-create'),

    path('rates/list/', RateListView.as_view(), name='rates-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
]

app/settings/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

import settings.settings

from currency.views import IndexView

schema_view = get_schema_view(
   openapi.Info(
      title="Tracky API",
      default_version='v1',
      description="Open Tracky API",
      terms_of_service="https://www.tracky.io/terms/",
      contact=openapi.Contact(email="tracky@tracky.io"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('auth/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('', IndexView.as_view(), name='homepage'),

    path('currency/', include('currency.urls')),
    path('api/currency/', include('currency.api.urls')),
    path('api/', include('account.api.urls')),

    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.settings.base.MEDIA_URL, document_root=settings.settings.base.MEDIA_ROOT)

app/currency/models.py
from _decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models

from currency.choices import RateCurrencyChoices


# Create your models here.


class Rate(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    currency = models.PositiveSmallIntegerField(
        choices=RateCurrencyChoices.choices,
        default=RateCurrencyChoices.USD
    )
    buy = models.DecimalField(
        max_digits=6, decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'), message="Exchange rate can't be smaller than zero")])
    sell = models.DecimalField(
        max_digits=6, decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'), message="Exchange rate can't be smaller than zero")])
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return f'Currency: {self.get_currency_display()}, Buy: {self.buy} (id: {self.id})'


class ContactUs(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=128)
    email_from = models.EmailField(max_length=48)
    subject = models.CharField(max_length=48)
    message = models.TextField()

    class Meta:
        verbose_name_plural = 'emails'
        ordering = ('-created', )

    def __str__(self):
        return f'From: {self.email_from}, Subject{self.subject}'


class Source(models.Model):
    name = models.CharField(max_length=64)
    code_name = models.CharField(max_length=64, unique=True)
    source_url = models.CharField(max_length=255)
    logo = models.FileField(
        default='sources_logos/source-default.svg',
        upload_to='sources_logos/'
    )

    def __str__(self):
        return self.name


class RequestResponseLog(models.Model):
    path = models.CharField(max_length=255)
    request = models.CharField(max_length=16)
    time = models.FloatField()

app/currency/forms.py
from django import forms

from currency.models import Rate, Source, ContactUs


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            "buy",
            "sell",
            "source",
            "currency"
        )

        widgets = {
            'buy': forms.TextInput(attrs={'placeholder': '38.80'}),
            'sell': forms.TextInput(attrs={'placeholder': '39.20'}),
        }

        labels = {
            "buy": "Buy rate",
            "sell": "Sell rate"
        }


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            "name",
            "source_url",
            "logo"
        )

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Pryvatbank'}),
            'source_url': forms.TextInput(attrs={'placeholder': 'https://www.privatbank.ua/'}),
        }

        labels = {
            "source_url": "Source URL",
        }


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs

        fields = (
            "name",
            "email_from",
            "subject",
            "message"
        )

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Petro Poroshenko'}),
            'email_from': forms.TextInput(attrs={'placeholder': 'example@tracky.com'}),
            'subject': forms.TextInput(attrs={'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'placeholder': 'Enter your message...'})
        }

        labels = {
            "email_from": "Email",
            "message": "Your message"
        }

app/currency/api/views.py
from django.core.cache import cache
from requests import Response

from rest_framework import viewsets, generics
from rest_framework.decorators import action
from rest_framework.permissions import AllowAny
from rest_framework.renderers import JSONRenderer
from django_filters import rest_framework as filters
from rest_framework import filters as rest_framework_filters

from currency import constants
from currency.api.mixins import IsSuperUserMixin
from currency.api.serializers import RateSerializer, SourceSerializer, ContactUsSerializer
from currency.choices import RateCurrencyChoices
from currency.filters import EmailsFilter, RateAPIFilter
from currency.models import Rate, Source, ContactUs


class RateViewSet(viewsets.ModelViewSet):
    queryset = Rate.objects.all().select_related('source')
    serializer_class = RateSerializer
    renderer_classes = (JSONRenderer,)
    permission_classes = (AllowAny,)
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
    )
    filterset_class = RateAPIFilter
    ordering_fields = ('id', 'created', 'buy', 'sell')

    @action(detail=False, methods=('GET',))
    def latest(self, request, *args, **kwargs):
        latest_rates = []

        cached_rates = cache.get(constants.LATEST_RATE_CACHE)
        if cached_rates:
            return Response(cached_rates)

        for source_obj in Source.objects.all():
            for currency in RateCurrencyChoices:
                latest = Rate.objects.filter(
                    source=source_obj,
                    currency=currency) \
                    .order_by('-created') \
                    .first()

                if latest:
                    latest_rates.append(RateSerializer(instance=latest).data)

        cache.set(constants.LATEST_RATE_CACHE, latest_rates, 60 * 60 * 24 * 7)

        return Response(latest_rates)


class SourceApiView(generics.ListAPIView):
    queryset = Source.objects.all()
    serializer_class = SourceSerializer
    renderer_classes = (JSONRenderer,)


class ContactUsViewSet(IsSuperUserMixin, viewsets.ModelViewSet):
    queryset = ContactUs.objects.all()
    serializer_class = ContactUsSerializer
    renderer_classes = (JSONRenderer,)
    filter_backends = (
        filters.DjangoFilterBackend,
        rest_framework_filters.OrderingFilter,
        rest_framework_filters.SearchFilter,
    )
    filterset_class = EmailsFilter
    ordering_fields = ('created', 'name')
    search_fields = ['name', 'email_from', 'subject']

    def get_permissions(self):
        if self.action == 'list':
            permission_classes = (IsSuperUserMixin,)
        else:
            permission_classes = (AllowAny,)
        return [permission() for permission in permission_classes]

app/currency/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django_filters.views import FilterView

from currency.filters import RateFilter, EmailsFilter
from currency.models import Rate, ContactUs, Source
from currency.forms import RateForm, SourceForm, ContactUsForm

from currency.mixins import MyPaginatorMixin


# Create your views here.


# @method_decorator(cache_page(60 * 5), name='dispatch')
class RateListView(MyPaginatorMixin, FilterView):
    template_name = 'rates_list.html'
    paginate_by = 10
    filterset_class = RateFilter

    def get_queryset(self):
        return Rate.objects.all().select_related('source')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query_params = {key: value for key, value in self.request.GET.items() if
                        key != 'page' and value}
        context['filter_pagination'] = urlencode(query_params)
        return context


class RateDetailView(LoginRequiredMixin, DetailView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'


class RateCreateView(SuccessMessageMixin, CreateView):
    form_class = RateForm
    template_name = 'rate_create.html'
    success_url = reverse_lazy('currency:rates-list')
    success_message = 'Rate was created successfully'


class RateUpdateView(UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    form_class = RateForm
    template_name = 'rate_update.html'
    success_url = reverse_lazy('currency:rates-list')
    success_message = 'Rate was updated successfully'
    queryset = Rate.objects.all()

    def test_func(self):
        return self.request.user.is_superuser


class RateDeleteView(UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    queryset = Rate.objects.all()
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rates-list')
    success_message = 'Rate was deleted successfully'

    def test_func(self):
        return self.request.user.is_superuser


class EmailListView(MyPaginatorMixin, FilterView):
    template_name = 'emails_list.html'
    paginate_by = 10
    filterset_class = EmailsFilter

    def get_queryset(self):
        return ContactUs.objects.all()


class ContactUsCreateView(SuccessMessageMixin, CreateView):
    form_class = ContactUsForm
    template_name = 'contact_us_create.html'
    success_url = reverse_lazy('currency:contact-us-create')
    success_message = 'Your message was sent successfully'

    def _send_mail(self):
        subject = 'User ContactUs'
        message = f'''
                    Request from: {self.object.name}.
                    Reply to email: {self.object.email_from}.
                    Subject: {self.object.subject}.
                    Body: {self.object.message}.
                '''
        from currency.tasks import send_mail
        send_mail.delay(subject, message)

    def form_valid(self, form):
        redirect = super().form_valid(form)
        self._send_mail()
        return redirect


class SourceListView(ListView):
    template_name = 'sources_list.html'

    def get_queryset(self):
        return Source.objects.all()


class SourceDetailView(DetailView):
    queryset = Source.objects.all()
    template_name = 'source_details.html'


class SourceCreateView(SuccessMessageMixin, CreateView):
    form_class = SourceForm
    template_name = 'source_create.html'
    success_url = reverse_lazy('currency:sources-list')
    success_message = 'Source was created successfully'


class SourceUpdateView(SuccessMessageMixin, UpdateView):
    form_class = SourceForm
    template_name = 'source_update.html'
    success_url = reverse_lazy('currency:sources-list')
    success_message = 'Source was updated successfully'
    queryset = Source.objects.all()


class SourceDeleteView(SuccessMessageMixin, DeleteView):
    queryset = Source.objects.all()
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:sources-list')
    success_message = 'Source was deleted successfully'


class IndexView(TemplateView):
    template_name = 'index.html'

app/currency/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tracky – {% block title %} {% endblock title %}</title>

    {% load django_bootstrap5 %}

    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'styles/custom.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>


    <link rel="stylesheet" href="https://unpkg.com/@jarstone/dselect/dist/css/dselect.css">
    <script src="https://unpkg.com/@jarstone/dselect/dist/js/dselect.js"></script>


    {% bootstrap_javascript %}

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.svg' %}"/>

</head>
<body class="d-flex flex-column min-vh-100 vh-100">

{% include 'includes/navbar.html' %}

<div class="container my-4">

    {% bootstrap_messages %}

    {% block content %}
    {% endblock content %}

</div>

{% include 'includes/footer.html' %}

</body>
</html>

app/currency/templates/contact_us_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create Contact Us
{% endblock title %}

{% block content %}

    <div class="row g-0 justify-content-center">
        <div class="card card-box col-md-9 col-xl-6">

            <div class="card-header">
                <h1 class="page-heading h2 my-2">Contact Us</h1>
            </div>

            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="">
                        {{ form.name|as_crispy_field }}
                        {{ form.email_from|as_crispy_field }}
                        {{ form.subject|as_crispy_field }}
                        {{ form.message|as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-primary">Send message</button>
                </form>
            </div>

        </div>
    </div>

{% endblock content %}

app/currency/templates/emails_list.html
{% extends 'base.html' %}

{% block title %}
    Emails
{% endblock title %}

{% block content %}

    <div class="row">
    <div class="col-6">
        <h1 class="page-heading">Emails</h1>
    </div>

    <div class="col-6 d-flex align-items-end justify-content-end">
        <div class="mb-3">
            {% include 'includes/filtering.html' %}
        </div>
    </div>
    </div>

    {% if not request.user.is_superuser %}
        <p>You don't have access to this page</p>
    {% else %}

        <div class="table-responsive">
            <table class="table table-hover table-bordered">
                <thead class="table-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">From</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Message</th>
                </tr>
                </thead>
                {% for email in object_list %}
                    <tr>
                        <td>{{ email.id }}</td>
                        <td class="text-nowrap">{{ email.email_from }}</td>
                        <td class="text-nowrap">{{ email.subject }}</td>
                        <td>{{ email.message }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% endif %}

    {% include 'includes/pagination.html' %}

{% endblock content %}

app/currency/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Homepage
{% endblock title %}

{% block content %}

    <section class="hero mt-5">
        <div class="container-fluid">
            <div class="row justify-content-center d-flex align-items-center">
                <div class="col-md-6 hero-text">
                    <h1 class="mb-3">Meet <span class="name">Tracky</span> — Exchange Rates Monitoring App</h1>
                    <p>Tracky is an exchange rates monitoring app that helps you keep track of currency exchange
                        rates in real-time. With Tracky, you can easily monitor the exchange rates of your favorite
                        currencies. Whether you’re a traveler, a business owner, or just someone who wants to stay
                        up-to-date with the latest exchange rates, Tracky has got you covered.</p>
                    {% if not request.user.is_authenticated %}
                        <a class="btn btn-primary" href="{% url 'account:signup' %}">Sign Up</a>
                        <a class="btn btn-outline-primary" href="{% url 'login' %}">Login</a>
                    {% else %}
                        <a class="btn btn-primary btn-lg" href="{% url 'currency:rates-list' %}">Browse Rates</a>
                    {% endif %}
                </div>
                <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img class="img-fluid hero-image" src="{% static 'Hero-illustration.png' %}">
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

app/currency/templates/rate_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create rate
{% endblock title %}

{% block content %}

    <h1 class="page-heading">Create a new rate</h1>

    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-md-6 col-lg-3 mb-0">
                {{ form.buy|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 col-lg-3 mb-0">
                {{ form.sell|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6 col-lg-3 mb-0">
                {{ form.source|as_crispy_field }}
            </div>
            <div class="form-group col-md-6 col-lg-3 mb-0">
                {{ form.currency|as_crispy_field }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>

    <script>

        dselect(document.querySelector('#id_dropdown_name'), {

            search: true
        });

    </script>

{% endblock content %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete rate
{% endblock title %}

{% block content %}

    <p>Do you really want to delete the rate with id {{ rate.id }}?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a class="btn btn-outline-primary" href="{% url 'currency:rates-list' %}">Back to all rates</a>
    </form>

{% endblock content %}

app/currency/templates/rate_details.html
{% extends 'base.html' %}

{% block title %}
    Rate details
{% endblock title %}

{% block content %}

    <h1 class="page-heading">Rate Details</h1>

    <table class="table table table-hover table-bordered mt-4">
        <thead class="table-light">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Buy</th>
            <th scope="col">Sell</th>
            <th scope="col">Source</th>
            <th scope="col">Currency</th>
            <th scope="col">Created</th>
        </tr>
        </thead>
        <tr>
            <td>{{ rate.id }}</td>
            <td>{{ rate.buy }}</td>
            <td>{{ rate.sell }}</td>
            <td><img src="{{ rate.source.logo.url }}"> <a href="{% url 'currency:source-details' rate.source.id %}"> {{ rate.source }}</a></td>
            <td>{{ rate.get_currency_display }}</td>
            <td>{{ rate.created }}</td>
        </tr>
    </table>

    <a href="{% url 'currency:rates-list' %}" type="button" class="btn btn-outline-primary">Back to all rates</a>

{% endblock content %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}
    Update rate
{% endblock title %}

{% block content %}

    <h1 class="page-heading">Update the rate with id {{ rate.id }}</h1>

    <div class="row my-3">
        <div class="col-md-3">
            <form method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>

{% endblock content %}

app/currency/templates/rates_list.html
{% extends 'base.html' %}

{% block title %}
    Rates
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-6">
            <h1 class="page-heading">Rates</h1>
        </div>

        <div class="col-6 d-flex align-items-center justify-content-end">

            <div class="mb-3 me-2">
                {% include 'includes/filtering.html' %}
            </div>

            <div>
                <a class="btn btn-outline-primary mb-3" href="{% url 'currency:rate-create' %}" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-plus-square-fill" viewBox="0 0 16 16">
                        <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"></path>
                    </svg>
                    New
                </a>
            </div>

        </div>

    </div>


    <div class="table-responsive">
        <table class="table table-hover table-bordered align-middle text-nowrap">
            <thead class="table-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Buy rate</th>
                <th scope="col">Sell rate</th>
                <th scope="col">Currency</th>
                <th scope="col">Source</th>
                {% if request.user.is_authenticated %}
                    <th scope="col">Actions</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for rate in object_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ rate.id }}</td>
                    <td>{{ rate.buy }}</td>
                    <td>{{ rate.sell }}</td>
                    <td>{{ rate.get_currency_display }}</td>
                    <td><img src="{{ rate.source.logo.url }}"> {{ rate.source }}</td>
                    {% if request.user.is_authenticated %}
                        <td>
                            <div class="btn-group">
                                <a type="button" class="btn btn-primary btn-sm"
                                   href="{% url 'currency:rate-details' rate.id %}">Details</a>
                                <button type="button" class="btn btn-primary btn-sm dropdown-toggle"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="visually-hidden">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'currency:rate-details' rate.id %}">Details</a>
                                    </li>
                                    {% if request.user.is_superuser %}
                                        <li><a class="dropdown-item" href="{% url 'currency:rate-update' rate.id %}">Update</a>
                                        </li>
                                        <li><a class="dropdown-item" href="{% url 'currency:rate-delete' rate.id %}">Delete</a>
                                        </li>
                                        </ul>
                                    {% endif %}
                            </div>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% include 'includes/pagination.html' %}

{% endblock content %}

app/currency/templates/source_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Create source
{% endblock title %}

{% block content %}

    <h1 class="page-heading">Create a new source</h1>

    <form method="post">
        {% csrf_token %}
        <div class="col-md-6 col-lg-3">
            {{ form.name|as_crispy_field }}
            {{ form.source_url|as_crispy_field }}
            {{ form.logo|as_crispy_field }}
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>

{% endblock content %}

app/currency/templates/source_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete source
{% endblock title %}

{% block content %}

    <p>Do you really want to delete the source with id {{ source.id }}?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, delete</button>
        <a class="btn btn-outline-primary" href="{% url 'currency:sources-list' %}">Back to all sources</a>
    </form>

{% endblock content %}

app/currency/templates/sources_list.html
{% extends 'base.html' %}

{% block title %}
    Sources
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-6">
            <h1 class="page-heading">Exchange Rates Sources</h1>
        </div>
        <div class="col-6 d-flex align-items-end justify-content-end">
            <a class="btn btn-outline-primary mb-3" href="{% url 'currency:source-create' %}" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-plus-square-fill" viewBox="0 0 16 16">
                    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"></path>
                </svg>
                Create a new source
            </a>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-hover table-bordered align-middle text-nowrap">
            <thead class="table-light">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">URL</th>
                {% if request.user.is_authenticated %}
                    <th scope="col">Actions</th>
                {% endif %}
            </tr>
            </thead>
            {% for source in object_list %}
                <tr>
                    <td>{{ source.id }}</td>
                    <td><img src="{{ source.logo.url }}" width="24"> {{ source.name }}</td>
                    <td><a href="{{ source.source_url }}">{{ source.source_url }}</a></td>
                    {% if request.user.is_authenticated %}
                        <td>
                            <div class="btn-group">
                                <a type="button" class="btn btn-primary btn-sm"
                                   href="{% url 'currency:source-details' source.id %}">Details</a>
                                <button type="button" class="btn btn-primary btn-sm dropdown-toggle"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                    <span class="visually-hidden">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item"
                                           href="{% url 'currency:source-details' source.id %}">Details</a></li>
                                    {% if request.user.is_superuser %}
                                        <li><a class="dropdown-item"
                                               href="{% url 'currency:source-update' source.id %}">Update</a></li>
                                        <li><a class="dropdown-item"
                                               href="{% url 'currency:source-delete' source.id %}">Delete</a></li>
                                        </ul>
                                    {% endif %}
                            </div>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock content %}